[[plugins]]
repo =  'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ディレクトリツリー表示
repo = 'preservim/nerdtree'
hook_add = """
source ~/.config/nvim/plugins/nerdtree.rc.vim
"""


[[plugins]] # ウィンドウサイズ変更
repo = 'simeji/winresizer'
hook_add = """
source ~/.config/nvim/plugins/winresizer.rc.vim
"""

[[plugins]] # ranger.vim の依存関係
repo = 'rbgrouleff/bclose.vim'

[[plugins]] # ディレクトリツリー
repo = "francoiscabrol/ranger.vim"
hook_add = """
source ~/.config/nvim/plugins/ranger.rc.vim
"""

[[plugins]] # vim パワーライン
repo = 'vim-airline/vim-airline'
hook_add = """
source ~/.config/nvim/plugins/vim-airline.rc.vim
"""
[[plugins]] # vim パワーライン
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # カラースキーム
repo = 'NLKNguyen/papercolor-theme'

[[plugins]] # 履歴ファイルの検索
repo = 'Shougo/unite.vim'
hook_add = """
source ~/.config/nvim/plugins/unite.rc.vim
"""

[[plugins]] # LSP
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]] #統合インターフェース
repo = "Shougo/denite.nvim"
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]] #fzf 本体
repo = "junegunn/fzf"
build = './install --all'

[[plugins]] #fzf と連携するvimプラグイン
repo = "junegunn/fzf.vim"
depends = ['fzf']
hook_add = """
source ~/.config/nvim/plugins/fzf.rc.vim
"""


[[plugins]] #which-key
repo = "liuchengxu/vim-which-key"
hook_add = """
source ~/.config/nvim/plugins/vim-which-key.rc.vim
"""

[[plugins]] #自動整形
repo = 'junegunn/vim-easy-align'
hook_add = """
source ~/.config/nvim/plugins/vim-easy-align.rc.vim
"""

[[plugins]] # git
repo = "tpope/vim-fugitive"


[[plugins]] # git
repo = "airblade/vim-gitgutter"

